{% set version = "1.8" %}

package:
  name: namedlist
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/namedlist/namedlist-{{ version }}.tar.gz
  sha256: 34f89fc992592c80b39a709e136edcf41ea17f24ba31eaf84a314a02c8b9bcef

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - namedlist
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://bitbucket.org/ericvsmith/namedlist
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: Similar to namedtuple, but instances are mutable.

extra:
  recipe-maintainers:
    - ocefpaf
